name: E2E tests
description: verify e2e tests
runs:
  using: "composite"
  steps:
    - uses: nrwl/nx-set-shas@v4
    - uses: './.github/actions/node-cache'
    - uses: './.github/actions/cypress-cache'
    - uses: './.github/actions/webpack-cache'
    - name: Install deps
      shell: bash
      run: npm i
    - name: Build packages
      shell: bash
      run: npm run build
    - name: Run e2e tests
      shell: bash
      run: npm run test:e2e
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: dist/cypress/examples/test-app-e2e/screenshots/

